name: Build & Push Frontend and Backend to ECR

on:
  push:
    branches: [main]

jobs:
  build-frontend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS \
          --password-stdin 219030552981.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and tag frontend image
        env:
          ECR_URI: 219030552981.dkr.ecr.us-east-1.amazonaws.com/my-ecr-frontend
          SHA_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_URI:latest -t $ECR_URI:$SHA_TAG .

      - name: Push frontend image
        env:
          ECR_URI: 219030552981.dkr.ecr.us-east-1.amazonaws.com/my-ecr-frontend
          SHA_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_URI:latest
          docker push $ECR_URI:$SHA_TAG

  build-backend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS \
          --password-stdin 219030552981.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and tag backend image
        env:
          ECR_URI: 219030552981.dkr.ecr.us-east-1.amazonaws.com/my-ecr-backend
          SHA_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_URI:latest -t $ECR_URI:$SHA_TAG .

      - name: Push backend image
        env:
          ECR_URI: 219030552981.dkr.ecr.us-east-1.amazonaws.com/my-ecr-backend
          SHA_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_URI:latest
          docker push $ECR_URI:$SHA_TAG

